### ISSUE TITLE
emacs lags when check runs 

### ISSUE THREAD

**Issue by joachimmathes** [akhramov/org-wild-notifier.el#25] opened 2019-09-18 18:16 UTC
* emacs version: 26.1
* org-wild-notifier version: 0.3.1

When org-wild-notifier-mode looks for TODOs in the agenda, emacs hangs for a short period. It's less than a second, but it interferes with user interaction like navigating the cursor through a file, for example.

I figured out, that the time period is independent of the agenda size. But that's all I can say, so far.

**Comment by akhramov** [comment] 2019-09-19 13:00
Thank you!

I was not reproduce the issue locally, though, I am pretty sure I was able to track the cause down. May I ask you to volunteer at testing the fix (#26)? 
Just load the updated file into your running instance of Emacs.

**Comment by joachimmathes** [comment] 2019-09-20 07:04
Thank you for your fast reply. I'm going to test the fix.

**Comment by akhramov** [comment] 2019-09-30 19:15
Alright, closing this as the fix landed to the master branch. The updated version (v0.3.2) should appear on MELPA soon.

Thanks!

**Closed by akhramov** 2019-09-30 19:15 UTC
