### ISSUE TITLE
Sentiel Error

### ISSUE THREAD

**Issue by IsaulGarcia** [akhramov/org-wild-notifier.el#48] opened 2021-08-20 20:34 UTC
`error in process sentinel: Symbol's function definition is void: -orfn`

I keep receiving this error when the time arise for a notification. This seems similar to some previous issues, but not exactly. If you need more information let me know, I am not well verse in elisp. 
Note:
If I run  ` (org-wild-notifier--notify "Test Notification")` It works perfectly, if that helps.

**Comment by akhramov** [comment] 2021-08-21 06:01
Hey, thanks.

It looks like https://github.com/magnars/dash.el a library that provides `-orfn` isn't installed for some reason (that should happen automatically since it's a dependency)

Can you try installing it manually just to see if it resolves the issue?
Are you using vanilla GNU/Emacs, or some distros like spacemacs?

**Comment by IsaulGarcia** [comment] 2021-08-23 13:19
Hey thanks, and sorry for the late reply.

Looks like the dash library was already installed. I reinstalled it yet I still get the same error.
And I'm using the spacemacs distro.

**Comment by chris-aeviator** [comment] 2021-11-29 13:16
Having the same issue on spacemacs - the module is not doing anything

**Comment by colonelpanic8** [comment] 2023-09-15 06:28
@IsaulGarcia @chris-aeviator I'd look in to how your load path is configured.

**Comment by colonelpanic8** [comment] 2023-09-15 06:30
Duplicate of #41

**Closed by colonelpanic8** 2023-09-15 06:30 UTC
